### PR TITLE
DM-31698: Move ConvertReferenceCatalog classes out of ingestIndex file

### PR DESCRIPTION
**Pull request by parejkoj**

### CODE REVIEW

**Review by erykoff — COMMENTED** [review]
This overlaps with my DM-36617, and I think might not be necessary because that deletes a lot of this code and more.

**Comment by parejkoj** [comment]
Should I wait for that ticket to be merged, and see what's left of this one?

**Comment by erykoff** [comment]
Yup, and that ticket has been merged so I wonder if anything is left?  Thanks!

**Comment by parejkoj** [comment]
You missed one!

**Comment by erykoff** [comment]
:embarrassed emoji:

**Pull request merged**
